-----------------------------------------
-- 변경사항 구문
-----------------------------------------

COMMENT ON COLUMN ALBAYA6.BOARD_DECLARE.BOARD_DECLARE_DATE IS '신고 날짜';
COMMENT ON COLUMN ALBAYA6.BOARD_DECLARE.REPORTED_MEMBER_NO IS '신고당한 회원 번호';
-----------------------------------------



/*알바 후기 게시글*/
CREATE TABLE "REVIEW_BOARD" (
	"REVIEW_BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REVIEW_TITLE"	NVARCHAR2(100)		NOT NULL,
	"REVIEW_BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REVIEW_BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REVIEW_BOARD_UPDATE_DATE"	DATE		NOT NULL,
	"REVIEW_BOARD_CODE"	NUMBER		NOT NULL
);

/*게시글 번호 시퀀스*/
CREATE SEQUENCE SEQ_REVIEW_BOARD_NO NOCACHE;

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "REVIEW_BOARD"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_TITLE" IS '게시글제목';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_CONTENT" IS '게시글내용';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_WRITE_DATE" IS '작성일';

COMMENT ON COLUMN "REVIEW_BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "REVIEW_BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부(Y,N)';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_UPDATE_DATE" IS '마지막 수정일';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_CODE" IS '1:일반 2:공지';

SEAQUENCE 

-- 게시글 신고
CREATE TABLE "BOARD_DECLARE" (
	"REVIEW_BOARD_DECLARE_NO"	NUMBER		NOT NULL,
	"REVIEW_BOARD_NO"	NUMBER		NOT NULL,
	"REVIEW_BOARD_CONTENT"	VARCHAR2(1500)		NOT NULL,
	"REVIEW_BOARD_CONDITION"	CHAR(1)	DEFAULT 0	NOT NULL
);

-- 게시글 신고 테이블 회원번호 추가
ALTER TABLE BOARD_DECLARE ADD MEMBER_NO NUMBER NOT NULL;

-- 게시글 신고 날짜  추가(24.05.29)
ALTER TABLE BOARD_DECLARE ADD BOARD_DECLARE_DATE DATE DEFAULT SYSDATE NOT NULL;
-- 신고 당한 회원번호 추가(24.05.29)
ALTER TABLE BOARD_DECLARE ADD REPORTED_MEMBER_NO NUMBER NOT NULL;

ALTER TABLE BOARD_DECLARE MODIFY (REPORTED_MEMBER_NO NOT NULL);


COMMENT ON COLUMN "BOARD_DECLARE"."REVIEW_BOARD_DECLARE_NO" IS '게시글 신고 번호';

COMMENT ON COLUMN "BOARD_DECLARE"."REVIEW_BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "BOARD_DECLARE"."REVIEW_BOARD_CONTENT" IS '게시글 신고 사유';

COMMENT ON COLUMN "BOARD_DECLARE"."REVIEW_BOARD_CONDITION" IS '0:처리제외/1:처리중/2:처리완료';

-- 게시글 타입(일반, 공지)
CREATE TABLE "BOARD_TYPE" (
	"REVIEW_BOARD_CODE"	NUMBER		NOT NULL,
	"REVIEW_BOARD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."REVIEW_BOARD_CODE" IS '1:일반 2:공지';

COMMENT ON COLUMN "BOARD_TYPE"."REVIEW_BOARD_NAME" IS '게시판 이름(일반/공지)';

-- 댓글 신고
CREATE TABLE "COMMENT_DECLARE" (
	"COMENT_DECLARE_NO"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_DECLARE_CONTENT"	VARCHAR2(1500)		NOT NULL,
	"COMMENT_DECLARE_CONDITION"	CHAR(1)	DEFAULT 0	NOT NULL
);
-- 댓글 신고 테이블 회원번호 추가
ALTER TABLE COMMENT_DECLARE ADD MEMBER_NO NUMBER NOT NULL;
ALTER TABLE COMMENT_DECLARE ADD COMMENT_DECLARE_DATE DATE DEFAULT SYSDATE NOT NULL;
-- 신고 당한 회원번호 추가(24.05.29)
ALTER TABLE COMMENT_DECLARE ADD REPORTED_MEMBER_NO NUMBER NOT NULL;
COMMIT;

COMMENT ON COLUMN "COMMENT_DECLARE"."COMMENT_NO" IS '댓글 번호';

COMMENT ON COLUMN "COMMENT_DECLARE"."COMMENT_DECLARE_CONTENT" IS '댓글 신고 사유';

COMMENT ON COLUMN "COMMENT_DECLARE"."COMMENT_DECLARE_CONDITION" IS '0:처리제외/1:처리중/2:처리완료';

--댓글 테이블
CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REVIEW_BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMENT_NO2"	NUMBER		NULL
);

/*댓글 번호 시퀀스*/
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제여부(Y,N)';

COMMENT ON COLUMN "COMMENT"."REVIEW_BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_NO2" IS '부모댓글번호';

-- 게시글 신고 내역
CREATE TABLE "MEMBER_DECLARE_CONDITION" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"DECLARE_NUMBER"	NUMBER	DEFAULT 0	NOT NULL,
	"SUSPEND_PERIOD"	DATE		NULL
);


COMMENT ON COLUMN "MEMBER_DECLARE_CONDITION"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "MEMBER_DECLARE_CONDITION"."DECLARE_NUMBER" IS '신고 횟수';

COMMENT ON COLUMN "MEMBER_DECLARE_CONDITION"."SUSPEND_PERIOD" IS '정지기간(관리자 처리 시점부터 예시로 7일까지)';

ALTER TABLE "REVIEW_BOARD" ADD CONSTRAINT "PK_REVIEW_BOARD" PRIMARY KEY (
	"REVIEW_BOARD_NO"
);

ALTER TABLE "BOARD_DECLARE" ADD CONSTRAINT "PK_BOARD_DECLARE" PRIMARY KEY (
	"REVIEW_BOARD_DECLARE_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"REVIEW_BOARD_CODE"
);

ALTER TABLE "COMMENT_DECLARE" ADD CONSTRAINT "PK_COMMENT_DECLARE" PRIMARY KEY (
	"COMENT_DECLARE_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "MEMBER_DECLARE_CONDITION" ADD CONSTRAINT "PK_MEMBER_DECLARE_CONDITION" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_DECLARE_CONDITION" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_DECLARE_CONDITION_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


ALTER TABLE REVIEW_BOARD MODIFY (REVIEW_TITLE VARCHAR2(100));

ALTER TABLE COMMENT_DECLARE ADD (DECLARE_BOARD_CODE CHAR(1));

--------------------/*게시판 종류(code) 추가*/
INSERT INTO BOARD_TYPE 
VALUES(1,'공지');

INSERT INTO BOARD_TYPE 
VALUES(2,'일반');

SELECT REVIEW_BOARD_CODE, REVIEW_BOARD_NAME
FROM BOARD_TYPE
ORDER BY REVIEW_BOARD_CODE;

/* 신고 확정 처리 구문*/
UPDATE BOARD_DECLARE
SET REVIEW_BOARD_CONDITION = 2
WHERE REVIEW_BOARD_CONDITION = 1
AND REVIEW_BOARD_DECLARE_NO = 206;

/* 신고 확정된 멤버 상태 변경구문*/
UPDATE MEMBER
SET MEMBER_STATUS = CASE
											WHEN MEMBER_STATUS = 4 THEN 1
											WHEN MEMBER_STATUS = 1 THEN 2
											WHEN MEMBER_STATUS = 2 THEN 3
											ELSE MEMBER_STATUS
										END
WHERE MEMBER_NO = (
	SELECT REPORTED_MEMBER_NO
	FROM BOARD_DECLARE
	WHERE REVIEW_BOARD_DECLARE_NO = 206
        )
--OR MEMBER_NO =(
--	SELECT REPORTED_MEMBER_NO    댓글 신고 부분...
--	FROM COMMENT_DECLARE
--	WHERE COMMENT_DECLARE_NO = 
--);

SELECT MEMBER_STATUS 
	FROM "MEMBER" m 
	WHERE MEMBER_NO = 32;
	

UPDATE BOARD_DECLARE SET 
REVIEW_BOARD_CONDITION = 1
WHERE REVIEW_BOARD_CONDITION =2;


UPDATE REVIEW_BOARD SET 
BOARD_DEL_FL = 'Y'
WHERE REVIEW_BOARD_NO = 
(SELECT REVIEW_BOARD_NO
FROM BOARD_DECLARE 
WHERE REVIEW_BOARD_DECLARE_NO=131);


/* 정지상태 회원 조회 구문...*/
SELECT MEMBER_NO, AUTHORITY_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_PHONE_NUMBER,
		TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') ENROLL_DATE,
		MEMBER_NAME, MEMBER_STATUS, MEMBER_GENDER, MEMBER_ADDRESS,
		TO_CHAR(LAST_MODIFIED_DATE, 'YYYY-MM-DD') LAST_MODIFIED_DATE,
		TO_CHAR(LAST_MODIFIED_PW_DATE, 'YYYY-MM-DD') LAST_MODIFIED_PW_DATE
FROM "MEMBER"
WHERE MEMBER_STATUS = 3;

/* 정지상태 회원 정상상태로 변경하는 구문 */
UPDATE "MEMBER" SET 
MEMBER_STATUS = 4
WHERE MEMBER_STATUS = 3;

SELECT MEMBER_STATUS 
FROM "MEMBER" 
WHERE MEMBER_NO =100;

SELECT COUNT(*)
FROM "MEMBER" 
WHERE MEMBER_STATUS = 3;

--------- 댓글 신고 ----------
/* 처리중인 신고 댓글 수*/
SELECT count(*) 
FROM COMMENT_DECLARE cd 
WHERE COMMENT_DECLARE_CONDITION =1;

/*댓글 신고 목록 조회*/
SELECT COMMENT_DECLARE_NO ,COMMENT_NO ,MEMBER_NO ,
			COMMENT_DECLARE_CONTENT ,COMMENT_DECLARE_CONDITION ,
			COMMENT_DECLARE_DATE ,REPORTED_MEMBER_NO 
FROM COMMENT_DECLARE
WHERE COMMENT_DECLARE_CONDITION = 1
ORDER BY COMMENT_DECLARE_NO ; 

/* 댓글 신고 구문*/
INSERT INTO COMMENT_DECLARE 
VALUES(
	#{commentDeclareNo},
	#{commentNo},
	#{memberNo},
	#{commentDeclareContent},
	DEFAULT,
	DEFAULT,
	(SELECT MEMBER_NO
	 FROM "COMMENT" 
	 WHERER COMMENT_NO #{commentNo}),
	DEFAULT)
	;

------------------------------

COMMIT;
ROLLBACK;
