CREATE TABLE "REVIEW_BOARD" (
	"REVIEW_BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REVIEW_TITLE"	NVARCHAR2(100)		NOT NULL,
	"REVIEW_BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REVIEW_BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REVIEW_BOARD_UPDATE_DATE"	DATE		NOT NULL,
	"REVIEW_BOARD_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "REVIEW_BOARD"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_TITLE" IS '게시글제목';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_CONTENT" IS '게시글내용';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_WRITE_DATE" IS '작성일';

COMMENT ON COLUMN "REVIEW_BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "REVIEW_BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부(Y,N)';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_UPDATE_DATE" IS '마지막 수정일';

COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BOARD_CODE" IS '1:일반 2:공지';

CREATE TABLE "BOARD_DECLARE" (
	"REVIEW_BOARD_DECLARE_NO"	NUMBER		NOT NULL,
	"REVIEW_BOARD_NO"	NUMBER		NOT NULL,
	"REVIEW_BOARD_CONTENT"	VARCHAR2(1500)		NOT NULL,
	"REVIEW_BOARD_CONDITION"	CHAR(1)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "BOARD_DECLARE"."REVIEW_BOARD_DECLARE_NO" IS '게시글 신고 번호';

COMMENT ON COLUMN "BOARD_DECLARE"."REVIEW_BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "BOARD_DECLARE"."REVIEW_BOARD_CONTENT" IS '게시글 신고 사유';

COMMENT ON COLUMN "BOARD_DECLARE"."REVIEW_BOARD_CONDITION" IS '0:처리제외/1:처리중/2:처리완료';

CREATE TABLE "BOARD_TYPE" (
	"REVIEW_BOARD_CODE"	NUMBER		NOT NULL,
	"REVIEW_BOARD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."REVIEW_BOARD_CODE" IS '1:일반 2:공지';

COMMENT ON COLUMN "BOARD_TYPE"."REVIEW_BOARD_NAME" IS '게시판 이름(일반/공지)';

CREATE TABLE "COMMENT_DECLARE" (
	"COMENT_DECLARE_NO"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_DECLARE_CONTENT"	VARCHAR2(1500)		NOT NULL,
	"COMMENT_DECLARE_CONDITION"	CHAR(1)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "COMMENT_DECLARE"."COMMENT_NO" IS '댓글 번호';

COMMENT ON COLUMN "COMMENT_DECLARE"."COMMENT_DECLARE_CONTENT" IS '댓글 신고 사유';

COMMENT ON COLUMN "COMMENT_DECLARE"."COMMENT_DECLARE_CONDITION" IS '0:처리제외/1:처리중/2:처리완료';

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REVIEW_BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMENT_NO2"	NUMBER		NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제여부(Y,N)';

COMMENT ON COLUMN "COMMENT"."REVIEW_BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_NO2" IS '부모댓글번호';

CREATE TABLE "MEMBER_DECLARE_CONDITION" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"DECLARE_NUMBER"	NUMBER	DEFAULT 0	NOT NULL,
	"SUSPEND_PERIOD"	DATE		NULL
);

COMMENT ON COLUMN "MEMBER_DECLARE_CONDITION"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "MEMBER_DECLARE_CONDITION"."DECLARE_NUMBER" IS '신고 횟수';

COMMENT ON COLUMN "MEMBER_DECLARE_CONDITION"."SUSPEND_PERIOD" IS '정지기간(관리자 처리 시점부터 예시로 7일까지)';

ALTER TABLE "REVIEW_BOARD" ADD CONSTRAINT "PK_REVIEW_BOARD" PRIMARY KEY (
	"REVIEW_BOARD_NO"
);

ALTER TABLE "BOARD_DECLARE" ADD CONSTRAINT "PK_BOARD_DECLARE" PRIMARY KEY (
	"REVIEW_BOARD_DECLARE_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"REVIEW_BOARD_CODE"
);

ALTER TABLE "COMMENT_DECLARE" ADD CONSTRAINT "PK_COMMENT_DECLARE" PRIMARY KEY (
	"COMENT_DECLARE_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "MEMBER_DECLARE_CONDITION" ADD CONSTRAINT "PK_MEMBER_DECLARE_CONDITION" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_DECLARE_CONDITION" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_DECLARE_CONDITION_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


ALTER TABLE REVIEW_BOARD MODIFY (REVIEW_TITLE VARCHAR2(100));


